# Generated by Django 4.0.4 on 2022-04-28 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_react_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='react',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
