# Generated by Django 4.0.3 on 2022-04-29 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AlterField(
            model_name='react',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
