# Generated by Django 4.0.3 on 2022-04-29 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_post_alter_react_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='react',
            name='name',
            field=models.CharField(max_length=10000000),
        ),
    ]
